Repository Haven-13/Haven-Urist, pull requests merged in 2021-09, with the labels that each got.

#77 Better regex-based style linting
  .github/workflows/ci.yml
  .vscode/settings.json
  check_regex.yaml
  code/_helpers/icons.dm
  code/_helpers/text.dm
  code/_helpers/vector.dm
  code/game/gamemodes/events/holidays/Christmas.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_interdiction.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_manipulation.dm
  code/game/objects/items/weapons/storage/storage_ui/tgui.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/culture_descriptor/culture/cultures.dm
  code/modules/culture_descriptor/culture/cultures_skrell.dm
  code/modules/culture_descriptor/culture/cultures_unathi.dm
  code/modules/culture_descriptor/faction/factions_unathi.dm
  code/modules/culture_descriptor/location/locations_human.dm
  code/modules/culture_descriptor/location/locations_unathi.dm
  code/modules/culture_descriptor/religion/religions_unathi.dm
  code/modules/economy/Events_Mundane.dm
  code/modules/events/communications_blackout.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/power/sensors/powernet_sensor.dm
  code/modules/urist/datums/uristlanguages.dm
  code/modules/urist/items/uristwar2.dm
  code/modules/urist/mob/robots.dm
  tools/ci/check_regex.py
  tools/requirements.txt
Labels: Tooling

#80 Add automatic localhost rank
  check_regex.yaml
  code/__defines/admin.dm
  code/controllers/configuration.dm
  code/modules/admin/banjob.dm
  code/modules/client/client_procs.dm
  config/config.txt
  config/example/config.txt
Labels: Feature, Backend

#79 Refactor `obj/screen` to `atom/movable/screen`
  code/_helpers/game.dm
  code/_onclick/click.dm
  code/_onclick/hud/ability_screen_objects.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/global_hud.dm
  code/_onclick/hud/gun_mode.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/map_view.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/evacuation/evacuation_pods.dm
  code/datums/cinematic.dm
  code/game/gamemodes/endgame/bluespace_jump/bluespace_jump.dm
  code/game/gamemodes/endgame/nuclear_explosion/nuclear_explosion.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/camera/camera.dm
  code/game/mecha/mecha.dm
  code/game/movietitles.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/client/client_defines.dm
  code/modules/client/ui_style.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/ui_modules/camera_monitor.dm
  code/modules/multiz/open_darkness.dm
  code/modules/organs/internal/species/nabber.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/photography.dm
  code/modules/species/species.dm
  code/modules/urist/gamemodes/infestation/aliens/harvester.dm
Labels: Refactor, Backend

#81 Minor `check_regex.py` bugfixes
  tools/ci/check_regex.py
Labels: Tooling, Bugfix

#82 Port tgstation hover-over text
  baystation12.dme
  check_regex.yaml
  code/__defines/flags.dm
  code/_helpers/text.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screen_tip.dm
  code/game/atoms.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf_null.dm
  code/game/turfs/unsimulated/beach.dm
  code/game/turfs/unsimulated/floor.dm
  code/interface/stylesheet.dm
  code/modules/client/preference_setup/global/preferences.dm
Labels: Port, Feature, Backend, UI

#83 Resprites the fuel port and oxygen wall closet
  icons/obj/walllocker.dmi
  icons/turf/shuttle.dmi
Labels: Sprites

#87 Fix HTML-UI runtimes
  code/game/machinery/machinery.dm
Labels: Bugfix, UI

#85 `map-view`-based preview in preferences
  code/_onclick/hud/map_view.dm
  code/_onclick/hud/plane_master.dm
  code/interface/skin.dmf
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preferences.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Refactor, Bugfix, Backend

#88 Fix missing synth/posi culture for Pluto
  Haven/Maps/TycloPluto/datums/lore/_module_lore_ah13.dm
  Haven/Maps/TycloPluto/datums/lore/cultures/cultures_machine.dm
  Haven/Maps/TycloPluto/datums/lore/species_overrides/machine.dm
  Haven/Maps/TycloPluto/datums/lore/strings_names.dm
  check_regex.yaml
Labels: Bugfix
